### ISSUE TITLE
[BUG] celeborn raft HA exception

### ISSUE THREAD

**Issue by conorzhao** [apache/incubator-celeborn#1231] opened 2023-02-13 12:27 UTC
### What is the bug(with logs or screenshots)?
Start three master instances, two of which frequently brush exception logs
![image](https://user-images.githubusercontent.com/27194698/218457133-0c528f6a-fcef-4b28-b6c3-7e6772ce7a2a.png)
It does not affect the operation of the job, but the log volume has soared, which seems to be caused by the exception of selecting the master of the raft
### How to reproduce the bug?
Steps to reproduce the bug.
start three master

Please help me see what the problem is
/cc @who-need-to-know

/assign @who-can-solve-this-bug

**Comment by FMX** [comment] 2023-02-13 12:48
Can you share your celeborn cluster version? The git commit id will be very helpful.

**Comment by BigdataGit** [comment] 2023-02-14 02:01
> Can you share your celeborn cluster version? The git commit id will be very helpful.

[v0.2.0-incubating-rc3](https://github.com/apache/incubator-celeborn/releases/tag/v0.2.0-incubating-rc3)

**Comment by BigdataGit** [comment] 2023-02-14 02:03
> Can you share your celeborn cluster version? The git commit id will be very helpful.

Is there a celeborn discussion group? Can you add me

**Comment by BigdataGit** [comment] 2023-02-14 02:05
![image](https://user-images.githubusercontent.com/27194698/218620032-da218a1e-9616-4942-b05b-7bd1b73941ef.png)

**Comment by FMX** [comment] 2023-02-14 02:14
We have slack channels and a DingTalk group. Feel free to reach us in a convenient way.

**Comment by BigdataGit** [comment] 2023-02-14 02:24
> We have slack channels and a DingTalk group. Feel free to reach us in a convenient way.

I can't find the contact information of DingTalk group, can you send me

**Comment by BigdataGit** [comment] 2023-02-14 02:24
> We have slack channels and a DingTalk group. Feel free to reach us in a convenient way.

I can't find the contact information of DingTalk group, can you send me

**Comment by lianneli** [comment] 2023-03-04 09:02
I need DingTalk group information too~

**Comment by waitinfuture** [comment] 2023-03-04 10:58
> I need DingTalk group information too~

Ding talk groupId: 41594456

**Comment by sunjincheng121** [comment] 2023-05-22 08:47
What is the current state of discussion on this issue? I would greatly appreciate it if you discuss this issue here, for that all of the open source participants can well know the state of this discussion. @waitinfuture @FMX  Thank you!

**Comment by waitinfuture** [comment] 2023-05-22 08:55
> What is the current state of discussion on this issue? I would greatly appreciate it if you discuss this issue here, for that all of the open source participants can well know the state of this discussion. @waitinfuture @FMX Thank you!

Hi @sunjincheng121 , thanks for paying attention, I believe this issue is fixed, @FMX could you offer more details?

**Comment by FMX** [comment] 2023-05-22 09:23
@sunjincheng121  Hi, this issue is fixed now. 
This issue is caused by a bug that prevents the master node from loading its snapshot.
Following are patch lists:
https://github.com/apache/incubator-celeborn/pull/996

**Comment by FMX** [comment] 2023-05-22 09:23
This issue is resolved. So I'll close this issue.

**Closed by FMX** 2023-05-22 09:23 UTC
Labels: bug
